name: Dependent Jobs Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start build
        run: echo "Building application..."

      - name: Simulate build process
        run: sleep 5

      - name: Build complete
        run: echo "Build finished successfully!"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start tests
        run: echo "Running tests..."

      - name: Simulate test process
        run: sleep 3

      - name: Test complete
        run: echo "All tests passed!"

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start deployment
        run: echo "Deploying application..."

      - name: Simulate deployment
        run: sleep 4

      - name: Deployment complete
        run: echo "Deployment finished successfully!"
